FROM golang:alpine

WORKDIR /app
COPY ./ /app

RUN go mod download

RUN go get github.com/githubnemo/CompileDaemon

ENTRYPOINT CompileDaemon --build="go build ./cmd/jt-slackbot" --command=./jt-slackbot