FROM golang:alpine

WORKDIR /app

COPY ./src /app

RUN go mod download

RUN go get github.com/githubnemo/CompileDaemon

ENTRYPOINT CompileDaemon --build="go build ./cmd/jt-slackbot-core" --command=./jt-slackbot-core